spring:
  application:
    name: mario-sample
  profiles:
    active: local

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.1.111:3306/hm-brunch
    username: test
    password: test
